language: node_js

node_js:
  - 10
  - 9
  - 8

install: npm install

script:
  - npm run react-cli && echo -e "\n\n\n"
  - npm run test && echo -e "\n\n\n"

after_success: echo "Success"

branches:
  only: master
